Fix on example FBLoginExample
facebook/facebook-android-sdk pull request #815
Opened 2020-08-15 07:59 UTC by newarifrh

Thanks for proposing a pull request!

To help us review the request, please complete the following:

- [X] sign [contributor license agreement](https://developers.facebook.com/opensource/cla)

## Pull Request Details

Initially when facebook_app_id (in activity) and facebook_app_id (in resource string) have the same value will display a warning, it should display a warning when fb_login_protocol_scheme does not contain facebook_app_id.

2020-08-31 22:43 UTC, alshamiri5 approved these changes

2020-09-04 07:04 UTC, mediagatewizard commented
From 43915032fd32586d93422990430e9783765428b6 Mon Sep 17 00:00:00 2001
From: Arif Rahman Hakim <16.9025@stis.ac.id>
Date: Sat, 15 Aug 2020 14:52:03 +0700
Subject: [PATCH] Fixed string checking fb_login_protocol_scheme &
 facebook_app_id

---
 .../main/java/com/facebook/fbloginsample/MainActivity.java   | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)

diff --git a/samples/FBLoginSample/src/main/java/com/facebook/fbloginsample/MainActivity.java b/samples/FBLoginSample/src/main/java/com/facebook/fbloginsample/MainActivity.java
index a629839de..d77fc1ec7 100644
--- a/samples/FBLoginSample/src/main/java/com/facebook/fbloginsample/MainActivity.java
+++ b/samples/FBLoginSample/src/main/java/com/facebook/fbloginsample/MainActivity.java
@@ -35,13 +35,12 @@
   private static final int RESULT_POSTS_ACTIVITY = 2;
   private static final int RESULT_PERMISSIONS_ACTIVITY = 3;
 
-  private static final String DEFAULT_FB_APP_ID = "ENTER_YOUR_FB_APP_ID_HERE";
-
   @Override
   protected void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     setContentView(R.layout.activity_main);
-    if (getResources().getString(R.string.facebook_app_id).equals(DEFAULT_FB_APP_ID)) {
+    // string fb login protocol schema must contain "fb" + facebook app id.
+    if (!getResources().getString(R.string.fb_login_protocol_scheme).contains(getResources().getString(R.string.facebook_app_id))) {
       showAlertNoFacebookAppId();
       return;
     }

2021-04-11 22:05 UTC, octaviana1 commented
@newarifrh

2021-09-08 20:02 UTC, xilosada requested changes
HI @newarifrh, thanks for your suggestion.  The original code checks if the `facebook_app_id` has been changed in strings.xml. If the app_id isn't replaced it  shows a dialog with the solution. This change reuses the same dialog for a different situation.

2021-09-10 12:28 UTC, closed without merging